/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/TroniclabLogo.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Gift_Item_V1.geometry}
        material={nodes.Gift_Item_V1.material}
        position={[-4.74, 0, 2.06]}
        scale={[0.07, 0.07, 0.07]}
      />
    </group>
  )
}

useGLTF.preload('/TroniclabLogo.glb')
