/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/troniclab_Mkeyholder.glb')
  return (
    <group ref={group} {...props} dispose={null}>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.001']}
        position={[1.58, 0.73, 0]}
        rotation={[0.07, -0.08, 1.23]}
      />
    </group>
  )
}

useGLTF.preload('/troniclab_Mkeyholder.glb')
